### ISSUE TITLE
Возможность использовать shell-инъекцию в ping

### ISSUE THREAD

**Issue by pbsphp** [ochoba-unity/hell-o-bot#3]
Для вызова команды ping используется функция system и вставляемый в нее аргумент команды. Если в качестве аргумента команды вставить "google.com; rm -rf /* " это может привести к нежелательным последствиям. Оп-оп, секурная бага. Пацаны обоссут за такое.

**Comment by ochoba-unity** [comment]
у модуля subprocess вроде бы есть call
